name: release-build

on:
  # manual trigger
  workflow_dispatch:
  # push trigger
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  # TEST
  pull_request:
    branches: 
      - master

jobs:
  build:
    name: Push Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Go modules cache
        uses: actions/cache@v2.1.6
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}
          registry: ghcr.io

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::v0.0.1
        #run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Publish images on GitHub Container Registry
        run: |
          make docker-push
          make docker-push-initcontainer
        env:
          IMG: ghcr.io/yokawasa/k8s-cronjob-prescaler:${{ steps.get_version.outputs.VERSION }}
          INIT_IMG: ghcr.io/yokawasa/k8s-cronjob-prescaler-initcontainer:1

      - name: Release Deployment YAML file
        run: make kustomize-release
        env:
          IMG: ghcr.io/yokawasa/k8s-cronjob-prescaler:${{ steps.get_version.outputs.VERSION }}
          INIT_IMG: ghcr.io/yokawasa/k8s-cronjob-prescaler-initcontainer:1

        # Get release information to determine id of the current release
      - name: Get Release
        id: get-release-info
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload deployment YAML file to GitHub release
      - name: Upload Deployment YAML file
        id: upload-deployment-yaml
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/yokawasa/k8s-cron-prescaler/releases/${{ steps.get-release-info.outputs.id }}/assets?name=k8s-cronjob-prescaler-${{ steps.get_version.outputs.VERSION }}.yaml
          asset_path: k8s-cronjob-prescaler-${{ steps.get_version.outputs.VERSION }}.yaml
          asset_name: k8s-cronjob-prescaler-${{ steps.get_version.outputs.VERSION }}.yaml
          asset_content_type: application/x-yaml
